src/Entity/Orders.php
<?php

namespace App\Entity;

use App\Repository\OrdersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrdersRepository::class)
 */
class Orders
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    const STATUS_ORDER = [
        0 => "en attente",
        1 => "validée"
    ];

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=ShipAddresses::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ShipAddress;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=ProductsOrder::class, mappedBy="orders", cascade={"persist"})
     */
    private $ProductsOrder;

    /**
     * @ORM\OneToOne(targetEntity=Factures::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $facture;

    public function __construct()
    {
        $this->ProductsOrder = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->reference = 1;
        $this->status = 0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getStatus(): ?string
    {
        return self::STATUS_ORDER[$this->status];
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }


    public function getShipAddress(): ?ShipAddresses
    {
        return $this->ShipAddress;
    }

    public function setShipAddress(?ShipAddresses $ShipAddress): self
    {
        $this->ShipAddress = $ShipAddress;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getFacture(): ?Factures
    {
        return $this->facture;
    }

    public function setFacture(Factures $facture): self
    {
        $this->facture = $facture;

        return $this;
    }

    /**
     * @return Collection|ProductsOrder[]
     */
    public function getProductsOrder(): Collection
    {
        return $this->ProductsOrder;
    }

    public function addProductsOrder(ProductsOrder $productsOrder): self
    {
        if (!$this->ProductsOrder->contains($productsOrder)) {
            $this->ProductsOrder[] = $productsOrder;
            $productsOrder->setOrder($this);
        }

        return $this;
    }

    public function removeProductsOrder(ProductsOrder $productsOrder): self
    {
        if ($this->ProductsOrder->removeElement($productsOrder)) {
            // set the owning side to null (unless already changed)
            if ($productsOrder->getOrder() === $this) {
                $productsOrder->setOrder(null);
            }
        }

        return $this;
    }



}

src/Controller/CheckoutController.php
<?php

namespace App\Controller;

use Dompdf\Dompdf;
use Stripe\Stripe;

use Dompdf\Options;
use App\Entity\Cart;
use App\Entity\Facture;
use App\Repository\UserRepository;
use App\Repository\OrderingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CheckoutController extends AbstractController
{
  
    /**
     * @Route("/create-checkout-session/{reference}", name="create-checkout-session")
     * 
     * Fonction permettant à l'utilisateur d'afficher la page de paiement Stripe
     * 
     * @return Response
     */
    public function payment($reference, OrderingRepository $or, EntityManagerInterface $manager):Response
    {
        $order = $or->findOneByOrderingReference($reference);

        $YOUR_DOMAIN = 'http://127.0.0.1:8000';
        $productsForStripe = [];

        // Permet d'afficher les informations relatives aux produits
        // Sur la page de paiement
        foreach($order->getProductOrderings()->getValues() as $cartLine){
            $productsForStripe[] = [
            'price_data' => [
                'currency' => 'eur',
                'product_data' => [
                'name' => $cartLine->getProduct()->getName(),
                ],
                'unit_amount' => $cartLine->getProduct()->getUnitPrice()*100,
            ],
            'quantity' => $cartLine->getQuantity(),
            ];
        }
        
        Stripe::setApiKey( $this->getParameter('app.secretKey'));
        $checkout_session = \Stripe\Checkout\Session::create([
        'payment_method_types' => ['card'],
        'line_items' => [[
            $productsForStripe
        ]],
        'mode' => 'payment',
        'success_url' => $YOUR_DOMAIN.'/success/{CHECKOUT_SESSION_ID}',
        'cancel_url' => $YOUR_DOMAIN.'/error/{CHECKOUT_SESSION_ID}',
        ]);

        $order->setStripeSessionId($checkout_session->id);
        $manager->flush();
        return new JsonResponse(['id' => $checkout_session->id]);
    }

    /**
     * @Route("/success/{stripeSessionId}", name="success")
     * 
     * Fonction qui affiche la page de succès de commande à un utilisateur
     * 
     * @return Response
     */
    public function success($stripeSessionId, OrderingRepository $or,  SessionInterface $session, EntityManagerInterface $manager, SerializerInterface $serializer):Response
    {

        $order = $or->findOneByStripeSessionId($stripeSessionId);
        // On vérifie que l'utilisateur est le bon
        if($this->getUser() != $order->getUser()){
            return $this->redirectToRoute('products_show');
        }

        if($order->getOrderingStatus() === 0){
            //je récupère la facture
            $factureJson = $session->get('facture');
            $facture = $serializer->deserialize($factureJson, Facture::class, 'json');
            $facture->setOrdering($order);
            $order->setFacture($facture);
            $manager->persist($facture);
    
            //je passe le status de la commande à payé
            $order->setOrderingStatus(1);
            
            //je retire des stock la qte de produit qui a été vendu
            foreach($order->getProductOrderings() as $productLine){
                $product = $productLine->getProduct();
                $quantity = $productLine->getQuantity();
                $value = $product->getUnitStock() - $quantity;
                $product->setUnitStock($value);
            }
            $manager->flush();
            
            //je vide le panier
            $cart = $session->get('cart', new Cart());
            $cart->clear();
        }
        // je récupère le total de la commande
        // et la quantité de produit total
        $total = $order->getTotal();
        $quantityTotal = $order->getQuantityTotal();
        
        return $this->render('checkout/success.html.twig', [
            'order' => $order,
            'total' => $total,
            'quantityTotal' => $quantityTotal,
        ]);
    }

    /**
     * @Route("/downloadPDF/{id}", name="dl_facture")
     * 
     * Fonction qui permet de download la facture
     * 
     * @return Response
     */
    public function dlPDF($id, OrderingRepository $or):Response
    {
        $order = $or->findOneById($id);
        
        $total = $order->getTotal();
        $quantityTotal = $order->getQuantityTotal();
        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);

        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('checkout/facture.html.twig', [
            'order' => $order,
            'total' => $total,
            'quantityTotal' => $quantityTotal,
            'title' => "Votre Facture"
        ]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("Facture".$order->getFacture()->getFactureReference(), [
            "Attachment" => true
        ]);

        return new Response('', 200, [  'Content-Type' => 'application/pdf',]);
    }

    /**
     * @Route("/error/{stripeSessionId}", name="error")
     * 
     * Fonction qui affiche une page d'erreur suite au paiement de Stripe
     * 
     * @param OrderingRepository $or
     * @param UserRepository $ur
     * @param EntityManagerInterface $manager
     * 
     * 
     * @return Response
     */
    public function error($stripeSessionId, OrderingRepository $or, UserRepository $ur, EntityManagerInterface $manager):Response
    {
        $order = $or->findOneByStripeSessionId($stripeSessionId);
        $user = $ur->findOneById($order->getUser()->getId());
        if(!$order || $user != $this->getUser()){
            return $this->redirectToRoute('home');
        }

        if($order->getOrderingStatus() === 0){
            $order->setOrderingStatus(2);
            $manager->flush();
        }
        $this->addFlash('danger', 'Une erreur est survenue lors de votre paiement, veuillez réessayer');

        return $this->render('checkout/error.html.twig');
    }

}

templates/checkout/error.html.twig
{% extends 'base.html.twig' %}

{% block title %}Error{% endblock %}
{% block stylesheets %}
    {{ parent() }}
{% endblock %}
{% block body %}
    {% block nav %}
        {{ parent() }}
    {% endblock %}
    <section>
        <h1 class="h3 mb-3 font-weight-normal text-center">Une erreur est survenue lors de votre commande</h1>
        <p>Retourner à votre <a href="{{ path('cart_show') }}" class="text-uppercase">panier</a>.</p>
    </section>
{% endblock %}

templates/checkout/facture.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
    </style>
</head>
<body>
    <section id="factureSection">
        <h1 class="h3 mb-3 font-weight-normal text-center">Votre commande a bien été effectuée</h1>
        <h2 class="h4 mb-3 font-weight-normal">Confirmation de la commande n° {{order.orderingReference}}</h2>
        <h2 class="h4 mb-3 font-weight-normal">Facture n° {{ order.facture.factureReference }}</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Prix</th>
                    <th>Quantité</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for item in order.productOrderings %}

                    <tr>
                        <td>{{ item.product.name ~ ' domaine ' ~ item.product.domain.name ~ ' ' ~ item.product.year }}</td>
                        <td>{{ item.product.unitprice|number_format(2,',') ~ '€' }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.product.unitprice * item.quantity ~ '€' }}</td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2" class="text-right">Total : </td>
                    <td>{{ quantityTotal }}</td>
                    <td>{{ total ~ '€'}}</td>
                    
                </tr>
            </tfoot>
        </table>

        <div class="container-address">
            <div class="address">
                <h3>Adresse de livraison</h3>
                <p>Nom: {{ order.shipAddress.lastname }}</p>
                <p>Prénom: {{ order.shipAddress.firstname }}</p>
                <p>Ville: {{ order.shipAddress.city }}</p>
                <p>Code Postal: {{ order.shipAddress.zipcode }}</p>
                <p>Adresse: {{ order.shipAddress.address }}</p>
            </div>
            <div class="address">
                <h3>Adresse de facturation</h3>
                <p>Nom: {{ order.facture.lastname }}</p>
                <p>Prénom: {{ order.facture.firstname }}</p>
                <p>Ville: {{ order.facture.city }}</p>
                <p>Code Postal: {{ order.facture.zipcode }}</p>
                <p>Adresse: {{ order.facture.address }}</p>
            </div>          
        </div>
    </section>

</body>
</html>

templates/checkout/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Récapitulatif de commande{% endblock %}
{% block stylesheets %}
    {{ parent() }}
{% endblock %}
{% block body %}
    {% block nav %}
        {{ parent() }}
    {% endblock %}
    <section class="container" id="recapSection">
        {% if items | length > 0 %}
            <h1 class="h3 mb-3 font-weight-normal text-center">Récapitulatif de la commande</h1>
            <h2 class="h4 mb-3 font-weight-normal">Panier</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Produit</th>
                        <th>Prix</th>
                        <th>Quantité</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    {% set subtotal = item.product.unitprice * item.quantity %}
                        <tr>
                            <td>{{ item.product.name }}</td>
                            <td>{{ item.product.unitprice|number_format(2,',') ~ '€' }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>{{ subtotal|number_format(2, ',') ~ '€' }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3" class="text-right">Total : </td>
                        <td>{{ total|number_format(2, ',') ~ '€'}}</td>
                        {% if app.user %}
                            <td> </td>
                        {% else %}
                            <td> </td>
                        {% endif %}
                    </tr>
                </tfoot>
            </table>
            <div class="container-address">
                <div class="address">
                    <h3>Adresse de livraison</h3>
                    <p>Nom: {{ order.shipAddress.lastname }}</p>
                    <p>Prénom: {{ order.shipAddress.firstname }}</p>
                    <p>Ville: {{ order.shipAddress.city }}</p>
                    <p>Code Postal: {{ order.shipAddress.zipcode }}</p>
                    <p>Adresse: {{ order.shipAddress.address }}</p>
                </div>
                <div class="address">
                    <h3>Adresse de facturation</h3>
                    <p>Nom: {{ facture.lastname }}</p>
                    <p>Prénom: {{ facture.firstname }}</p>
                    <p>Ville: {{ facture.city }}</p>
                    <p>Code Postal: {{ facture.zipcode }}</p>
                    <p>Adresse: {{ facture.address }}</p>
                </div>          
            </div>
            {% if app.user %}
                <button class="btn btn-primary" id="checkout-button">Checkout</button>
            {% else %}
                <p><a href="{{ path('app_login') }}" class="btn btn-primary">Se connecter</a></p>
            {% endif %}
        {% else %}
            <p>Votre panier est vide.</p>
        {% endif %}
    </section>
{% endblock %}
{% block javascripts %}
    <script type="text/javascript">
        // Create an instance of the Stripe object with your publishable API key
        var stripe = Stripe('{{ public_key }}');
        var checkoutButton = $('#checkout-button');


        checkoutButton.on('click', function() {
            // Create a new Checkout Session using the server-side endpoint you
            // created in step 3.
            fetch("/create-checkout-session/{{ reference }}", {
                method: 'POST',
            })
            .then(function(response) {
                return response.json();
            })
            .then(function(session) {
                return stripe.redirectToCheckout({ sessionId: session.id });
            })
            .then(function(result) {
                // If `redirectToCheckout` fails due to a browser or network
                // error, you should display the localized error message to your
                // customer using `error.message`.
                if (result.error) {
                alert(result.error.message);
                }
            })
            .catch(function(error) {
                console.error('Error:', error);
            });
        });
    </script>

{% endblock %}

templates/checkout/recap.html.twig
{% extends 'base.html.twig' %}

{% block title %}Récapitulatif de commande{% endblock %}
{% block stylesheets %}
    {{ parent() }}
{% endblock %}
{% block body %}
    {% block nav %}
        {{ parent() }}
    {% endblock %}
    <section class="container" id="recapSection">
        {% if items | length > 0 %}
            <h1 class="h3 mb-3 font-weight-normal text-center">Récapitulatif de la commande</h1>
            <h2 class="h4 mb-3 font-weight-normal">Panier</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Produit</th>
                        <th>Prix</th>
                        <th>Quantité</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    {% set subtotal = item.product.unitprice * item.quantity %}
                        <tr>
                            <td>{{ item.product.name ~ " " ~ item.product.year ~ " Domaine " ~ item.product.domain.name|title }}</td>
                            <td>{{ item.product.unitprice|number_format(2,',') ~ '€' }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>{{ subtotal|number_format(2, ',') ~ '€' }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3" class="text-right">Total : </td>
                        <td>{{ total|number_format(2, ',') ~ '€'}}</td>
                        {% if app.user %}
                            <td> </td>
                        {% else %}
                            <td> </td>
                        {% endif %}
                    </tr>
                </tfoot>
            </table>
            <div class="container-address">
                <div class="address">
                    <h3>Adresse de livraison</h3>
                    <p>Nom: {{ order.shipAddress.lastname }}</p>
                    <p>Prénom: {{ order.shipAddress.firstname }}</p>
                    <p>Ville: {{ order.shipAddress.city }}</p>
                    <p>Code Postal: {{ order.shipAddress.zipcode }}</p>
                    <p>Adresse: {{ order.shipAddress.address }}</p>
                </div>
                <div class="address">
                    <h3>Adresse de facturation</h3>
                    <p>Nom: {{ facture.lastname }}</p>
                    <p>Prénom: {{ facture.firstname }}</p>
                    <p>Ville: {{ facture.city }}</p>
                    <p>Code Postal: {{ facture.zipcode }}</p>
                    <p>Adresse: {{ facture.address }}</p>
                </div>          
            </div>
            {% if app.user %}
                <button class="btn btn-primary" id="checkout-button">Checkout</button>
            {% else %}
                <p><a href="{{ path('app_login') }}" class="btn btn-primary">Se connecter</a></p>
            {% endif %}
        {% else %}
            <p>Votre panier est vide.</p>
        {% endif %}
    </section>
{% endblock %}
{% block javascripts %}
    <script type="text/javascript">
        // Create an instance of the Stripe object with your publishable API key
        var stripe = Stripe('{{ public_key }}');
        var checkoutButton = $('#checkout-button');


        checkoutButton.on('click', function() {
            // Create a new Checkout Session using the server-side endpoint you
            // created in step 3.
            fetch("/create-checkout-session/{{ reference }}", {
                method: 'POST',
            })
            .then(function(response) {
                return response.json();
            })
            .then(function(session) {
                return stripe.redirectToCheckout({ sessionId: session.id });
            })
            .then(function(result) {
                // If `redirectToCheckout` fails due to a browser or network
                // error, you should display the localized error message to your
                // customer using `error.message`.
                if (result.error) {
                alert(result.error.message);
                }
            })
            .catch(function(error) {
                console.error('Error:', error);
            });
        });
    </script>

{% endblock %}

templates/checkout/success.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande effectuée{% endblock %}
{% block stylesheets %}
    {{ parent() }}
{% endblock %}
{% block body %}
    {% block nav %}
        {{ parent() }}
    {% endblock %}
    <section id="factureSection" class="container">
        <h1 class="h3 mb-3 font-weight-normal text-center">Votre commande a bien été effectuée</h1>
        <h2 class="h4 mb-3 font-weight-normal">Confirmation de la commande n° {{order.orderingReference}}</h2>
        <h2 class="h4 mb-3 font-weight-normal">Facture n° {{ order.facture.factureReference }}</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Prix</th>
                    <th>Quantité</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for item in order.productOrderings %}
                {% set subtotal = item.product.unitprice * item.quantity %}
                    <tr>
                        <td>{{ item.product.name ~ " " ~ item.product.year ~" Domaine " ~ item.product.domain.name|title}}</td>
                        <td>{{ item.product.unitprice|number_format(2, ',') ~ '€' }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ subtotal|number_format(2, ',') ~ '€' }}</td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2" class="text-right">Total : </td>
                    <td>{{ quantityTotal }}</td>
                    <td>{{ total|number_format(2, ',') ~ '€'}}</td>
                    
                </tr>
            </tfoot>
        </table>

        <div class="container-address">
            <div class="address">
                <h3>Adresse de livraison</h3>
                <p>Nom: {{ order.shipAddress.lastname }}</p>
                <p>Prénom: {{ order.shipAddress.firstname }}</p>
                <p>Ville: {{ order.shipAddress.city }}</p>
                <p>Code Postal: {{ order.shipAddress.zipcode }}</p>
                <p>Adresse: {{ order.shipAddress.address }}</p>
            </div>
            <div class="address">
                <h3>Adresse de facturation</h3>
                <p>Nom: {{ order.facture.lastname }}</p>
                <p>Prénom: {{ order.facture.firstname }}</p>
                <p>Ville: {{ order.facture.city }}</p>
                <p>Code Postal: {{ order.facture.zipcode }}</p>
                <p>Adresse: {{ order.facture.address }}</p>
            </div>          
        </div>
        <p>
            <a target="_blank" href="{{ path('dl_facture', {'id': order.id }) }}" class="btn btn-primary">Télécharger la facture</a>
        </p>
    </section>
{% endblock %}